# Generated by Django 3.2.9 on 2021-12-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('sponsor', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.category')),
            ],
        ),
        migrations.CreateModel(
            name='CompDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdimgurl', models.ImageField(default='', upload_to='')),
                ('cdurl', models.CharField(max_length=100)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.comp')),
            ],
        ),
    ]
